### ISSUE TITLE
Docker: broken default master.yaml

### ISSUE THREAD

**Issue by Shnatsel** [opencollab/debile#12]
The default contrib/clemux/docker/debile-master/master.yaml seems to specify the wrong path to PGP keyring. Currently it is "/srv/debile/keyring.pgp"; it should be either "/srv/debile/.gnupg/pubring.gpg" or, if I'm building the data container wrong, "/srv/debile/keyring".

**Comment by mdimjasevic** [comment]
This has been handled with a pull request #37 .
